# -*- coding: utf-8 -*-
"""Consultas com BigQuery

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHRcDRWeehnUSw8OXx7sUjDM0C6yVPH5
"""

from google.colab import auth
auth.authenticate_user()

!pip install google-cloud-bigquery

from google.cloud import bigquery

project_id = "orbital-ego-400021" # Substitua pelo ID do seu projeto no Google Cloud
client = bigquery.Client(project=project_id)

query = '''SELECT * FROM `orbital-ego-400021.Teste12.teste12` LIMIT 10'''
query_job = client.query(query)
results = query_job.result()
for row in results:
    print(row)

