# -*- coding: utf-8 -*-
"""Consultas e Interações Através do Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sP22vsubdRIZwM7RabuiCkyFQIZt-E_Z
"""

from google.colab import auth
from google.cloud import bigquery
from google.colab import data_table

project = 'orbital-ego-400021'
location = 'US'
client=bigquery.Client(project=project, location = location)
data_table.enable_dataframe_formatter()
auth.authenticate_user()

job = client.get_job('bquxjob_445f9fdd_18b1c7b087f')
results = job.to_dataframe()
results