# -*- coding: utf-8 -*-
"""Recomendações com Algoritimo ALS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCmJGqQwabXACVovtEvzSriPnTMsqs7O

#1 Configurando bibliotecas e dependencias
"""

!pip install pyspark
!pip install findspark

# instalar as dependências
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
!tar xf spark-2.4.4-bin-hadoop2.7.tgz

from pyspark.sql import SparkSession
from pyspark.ml.evaluation import RegressionEvaluator #evaluation é a biblioteca para verificação da qualidade do modelo
from pyspark.ml.recommendation import ALS # ALS é o modelo de recomendação que será utilizadp
from pyspark.sql import Row #row é o formato que o ALS trabalha, row conterá o id do usuario, id filme, nota e timestamp

spark = SparkSession.builder.master('local[*]').getOrCreate()